services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    LoyaltyProgram\Domain\:
        resource: '../../../src/LoyaltyProgram/Domain/'

    LoyaltyProgram\Application\:
        resource: '../../../src/LoyaltyProgram/Application/'

    LoyaltyProgram\Infrastructure\:
        resource: '../../../src/LoyaltyProgram/Infrastructure/'

    LoyaltyProgram\Infrastructure\Controller\:
        resource: '../../../src/LoyaltyProgram/Infrastructure/Controller/'
        tags: ['controller.service_arguments']
