doctrine:
    dbal:
        connections:
            default:
                driver: 'pdo_pgsql'
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '15'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
        types:
            enum_invitation_status: Invitation\Infrastructure\DataBaseType\DoctrineInvitationStatusType

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Auth:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Auth/Domain'
                prefix: Auth\Domain\
                alias: Auth\Domain
            LoyaltyProgram:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/LoyaltyProgram/Domain'
                prefix: LoyaltyProgram\Domain\
                alias: LoyaltyProgram\Domain
            Invitation:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Invitation/Domain'
                prefix: Invitation\Domain\
                alias: Invitation\Domain
            ClientPurchases:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/ClientPurchases/Domain'
                prefix: ClientPurchases\Domain\
                alias: ClientPurchases\Domain
            Promocodes:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Promocodes/Domain'
                prefix: Promocodes\Domain\
                alias: Promocodes\Domain
        schema_ignore_classes:
            - 'LoyaltyProgram\Domain\Partner'
            - 'Invitation\Domain\Partner'
            - 'Invitation\Domain\LoyaltyProgram'
            - 'ClientPurchases\Domain\Client'
            - 'ClientPurchases\Domain\LoyaltyProgram'
            - 'ClientPurchases\Domain\Partner'
            - 'ClientPurchases\Domain\LoyaltyProgramClient'

when@test:
    doctrine:
        dbal:
            connections:
                default:
                    dbname_suffix: '_test'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
