auth:
    resource:
        path: ../src/Auth/Infrastructure/Controller/
        namespace: Auth\Infrastructure\Controller
    type: attribute

statistics:
    resource:
        path: ../src/Statistic/Infrastructure/
        namespace: Statistic\Infrastructure
    type: attribute

kernel:
    resource: ../src/SharedKernel/Framework/Kernel.php
    type: attribute

api_login_check:
    path: /api/login_check