services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Tests\:
        resource: '../tests/'

#    Tests\Fake\DataFixtures\:
#        resource: '../tests/Fake/DataFixtures/TestFixtures.php'
